### ISSUE TITLE
Create and Publish Lesson Sets Incomplete

### ISSUE THREAD

**Issue by noahcarrier** [noahcarrier/FinWise#2]
https://github.com/noahcarrier/FinWise/blob/1067245b14f3f2e313bfe9c10972e8dc75294935/src/pages/create-flashcards.tsx#L110

Code attempting to gather HTML data on cards created by the user and sending to the database has been created, most of which is specifically on the backend branch in files create-flashcards.tsx and createFlashcards.ts.

I've been continuing to work at understanding how to tackle this issue between the different technologies we're using, but without being able to verify if these methods are working or correct, would like further support on this specific task

**Comment by zhiyan114** [comment]
Some issues:
1. For pages, if you're going to import files that's intended to be run on server, you should and only call it inside `getServerSideProps`. Reason is that if you don't do so, the other source code will also be bundled into runtime client script (which will unnecessarily increase bundle size and security risk since now the server code can be viewed by anyone accessing the script). 
2.  NJS latest release does have server action, which would make this an appropriate use. Since we're using the old page method, all calls should be done via `getServerSideProps` then have the client props render what the function returns. Prisma client would also throw an error since we're technically calling it from a client (browser) rather than the server environment.
3. Some react usage tip: you don't have to use `document.getElementById(...)`, that's for native js or when we need to do something niche. Use [React Ref](https://react.dev/learn/referencing-values-with-refs) instead. You also dont need `document.createElement(...)`. Remember this is react, you can just create a component and pass down the info via props and I'll do the rendering for you.

Refactored it for you, just need to fix some of the error stuff and test to see if it works as before: https://github.com/noahcarrier/FinWise/commit/c24b16c8eea12fb173a2683769ebae68d1642e21

**Comment by noahcarrier** [comment]
@zhiyan114 amazing, thank you for the support and changes. going to be reviewing these changes today.

**Comment by noahcarrier** [comment]
issue resolved 4/29/24
